### ISSUE TITLE
Bad error messages for unresolvable forward references

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#14]
If untypy cannot resolve a forward reference, the error messages are pretty bad.

Example:

```python
class Test:
    def __init__(self, foo: 'Foo'):
        pass
    def __repr__(self):
        return 'Test'

class FooX:
    pass

t = Test(FooX())
print(t)
```

Run with `PYTHONPATH=site-lib/ python3 src/runYourProgram.py test-data/testForwardRef2.py`. Output:

```
Traceback (most recent call last):
  File "test-data/testForwardRef2.py", line 10, in <module>
    t = Test(FooX())
  File "/Users/swehr/devel/write-your-python-program/python/site-lib/untypy/patching/__init__.py", line 68, in lazy_typechecked
    c.inner = TypedFunctionBuilder(fn, DefaultCreationContext(
  File "/Users/swehr/devel/write-your-python-program/python/site-lib/untypy/util/typedfunction.py", line 26, in __init__
    annotations = typing.get_type_hints(inner, include_extras=True)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1469, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 555, in _evaluate
    self.__forward_value__ = _eval_type(
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 551, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Foo' is not defined
```

**Comment by skogsbaer** [comment]
Another example with records:

```python
from wypp import *

@record
class Test:
    foo: 'FooX'

class Foo:
    def __repr__(self):
        return 'Foo'

t = Test(Foo())
print(t)
```

Run with `PYTHONPATH=site-lib/ python3 src/runYourProgram.py test-data/testForwardRef4.py`. Output:

```
Traceback (most recent call last):
  File "test-data/testForwardRef4.py", line 11, in <module>
    t = Test(Foo())
  File "/Users/swehr/devel/write-your-python-program/python/site-lib/untypy/patching/__init__.py", line 68, in lazy_typechecked
    c.inner = TypedFunctionBuilder(fn, DefaultCreationContext(
  File "/Users/swehr/devel/write-your-python-program/python/site-lib/untypy/util/typedfunction.py", line 26, in __init__
    annotations = typing.get_type_hints(inner, include_extras=True)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1469, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 555, in _evaluate
    self.__forward_value__ = _eval_type(
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 551, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'FooX' is not defined
```

**Comment by skogsbaer** [comment]
The expected output in both cases would be to refer to the class `Test` pointing to the unresolvable type annotation.
