### ISSUE TITLE
maximum recursion depth reached

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#47]
Test

~~~python
from wypp import *

class C:
    def foo(self, other: C) -> C:
        return other

c = C()
check(c.foo(c), c)
~~~

Ausgabe

~~~
Traceback (most recent call last):
  File "test-data/testClassRecursion.py", line 8, in <module>
    check(c.foo(c), c)
  File "/Users/swehr/.pyenv/versions/3.9.7/lib/python3.9/inspect.py", line 335, in getmembers
    names = dir(object)
RecursionError: maximum recursion depth exceeded while calling a Python objects
~~~

**Comment by skogsbaer** [comment]
Test case: test-data/testClassRecursion.py
