### ISSUE TITLE
Bad error message when writing type list[int] as list(int)

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#61]
The following code 

~~~
def foo(l: list(int)) -> int:
    return len(l)
check(foo([1,2,3]), 3)
~~~

gives this very bad error message:

~~~
Traceback (most recent call last):
  File "test-data/testWrongParens.py", line 1, in <module>
    def foo(l: list(int)) -> int:
  File "/Users/swehr/.pyenv/versions/3.9.7/lib/python3.9/typing.py", line 1469, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/Users/swehr/.pyenv/versions/3.9.7/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/swehr/.pyenv/versions/3.9.7/lib/python3.9/typing.py", line 551, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not iterable
~~~

I had two students with this mistake and they were frustrated by the error message.

**Comment by CodeSteak** [comment]
Hmm ... In the annotation list(int) tries to construct a list from an `int`, but lists can only be made from iterables, but `type' object is not iterable`.

Probably best to check for this error message and show a hint.
