### ISSUE TITLE
TypeError: slice indices must be integers or have an __index__ method

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#92]
There is a bug in the list wrapper. Consider the following code:

```
from wypp import *

def get(l: list[int]) -> int:
    x = l.index(2)
    return x

print(get([1,2,3]))
```

Executing this code gives the following error:

```
Traceback (most recent call last):
  File "test-data/testBugSliceIndices.py", line 7, in <module>
    print(get([1,2,3]))
  File "test-data/testBugSliceIndices.py", line 4, in get
    x = l.index(2)
TypeError: slice indices must be integers or have an __index__ method
```

**Comment by skogsbaer** [comment]
@CodeSteak I tried to fix the bug but failed. 

The problem is that the wrapper in wrappedclass calls the index method with default arguments retrieved via `bindings.apply_defaults()`. When running the code, the default arguments are start=None, stop=None but they should be start=0 and stop=9223372036854775807

I'm wondering whether we need to supply the default arguments anyway. But simply omitting them leads to other problems.

Could you help?
